#ifndef MY_H       
#define MY_H
#include <iostream>
#include <fstream>
#include <vector>
#include <iomanip>
#include <string>
#include <algorithm>
#include <ctime>
#include <chrono>
#include <numeric>
#include <random>
#include <sstream>
#include <windows.h>
#include <cassert>
#include <memory>
#include <utility>

using std::cout;
using std::cin;
using std::string;
using std::vector;
using std::endl;
using std::fixed;
using std::setprecision;
using std::left;
using std::setw;
using std::sort;
using std::ifstream;
using std::ofstream;
using std::transform;
using std::exception;
using std::cerr;
using std::invalid_argument;
using std::out_of_range;
using std::to_string;
using namespace std::chrono;
using std::accumulate;
using std::random_device;
using std::mt19937;
using std::uniform_int_distribution;
using std::uniform_real_distribution;
using std::runtime_error;
using std::stringstream;
using std::ios;
using std::copy_if;
using std::back_inserter;
using std::remove_if;
using std::istringstream;
using std::move;
using std::ostream;
using std::istream;
using std::getline;
using std::abs;
using std::logic_error;
using std::unique_ptr;
using std::make_unique;

#endif 